### ISSUE TITLE
Garage Door 2fa?

### ISSUE THREAD

**Issue by bverenkoff** [homebridge-plugins/homebridge-gsh#3]
**Describe Your Problem:**
The docs mention garage doors require 2fa. I know what 2fa is, but where specifically. My Google account is 2fa protected. I’m not sure how to pin protect the garage door itself. Is there any more help on this topic?

**Comment by bverenkoff** [comment]
Disregard, I see in your advanced settings there is a PIN code 2fa. 

Any easy way to bypass that?

**Comment by NorthernMan54** [comment]
As garage doors are a potential security issue, google requires 2fa

`Secondary user verification with PIN must be implemented for all the device types and traits that if unintentionally used can put the home in a substantial risk state.`

https://developers.home.google.com/cloud-to-cloud/enhancements/secondary-user-verification
