### ISSUE TITLE
TV marked as light

### ISSUE THREAD

**Issue by vespino** [homebridge-plugins/homebridge-gsh#8]
First: glad this project is back! I moved to DZGA but that involved a lot more effort and a hole in my firewall.

Second: I have 4 lights in my living room and 1 TV. When I tell Google to turn on the lights, 5 devices are turned on instead of 4. The 4 lights show as lights and the TV (a switch) is shown as an on/off switch. My devices come from Domoticz btw.

**Comment by NorthernMan54** [comment]
What does the Google Home App show for the TV? 

This is from an outlet I have - Which google does not consider to be a light

![image](https://github.com/user-attachments/assets/322b396e-b2d6-4820-b1e6-c470f301dc17)

And this is a light switch - Which Google considers a light

![image](https://github.com/user-attachments/assets/a732de8c-15b9-4a55-b0ee-0ad8b4af4658)

**Comment by vespino** [comment]
It’s very contradictive, the icon is a light bulb, but the name is schakelaar which translates to switch.

![IMG_4176](https://github.com/user-attachments/assets/74e85e21-58a6-48ad-bf35-b3bbea25364a)
![IMG_4177](https://github.com/user-attachments/assets/c40cef6e-08a5-4bec-901d-5f3abc3bf3be)

**Comment by NorthernMan54** [comment]
With Domoticz, can you tell the device to be an outlet type and not a switch type?

**Comment by vespino** [comment]
It's set like this:
![afbeelding](https://github.com/user-attachments/assets/bbd394f8-7460-4f7d-89fc-8b674d705571)

So it's not "a light" or "an appliance", but on of off. It used to work fine a while ago. Don't know when this changed.

Weird thing is, Homebridge does show it was a switch instead of a light:
![afbeelding](https://github.com/user-attachments/assets/6adce2ff-1963-4593-b6db-2a9d6343c3ce)

**Comment by NorthernMan54** [comment]
Well you have 3 spots where a change could have occurred if you are confident this is how it was working before.

1 - the domiticz plugin, config or code could have changed and this is now a switch and not an outlet.

2 - Google changed something on the backend…..

3 - A recent change to the gsh plugin changed the switch behaviour.

for the gsh plugin it may be easy to check if the behaviour changed, just install an older version to see if the behaviour changes back.  I did look at the changes I made recently, and saw nothing like this, but you never know.

PS based on the testing I did, Google considers lightbulbs and switches as lights.  But not outlets.

**Comment by vespino** [comment]
I have been using DZGA for a while and that did pick up the devices correctly. That also has a way of changing the device type if not correct. I’ll take a look at the Domoticz plugin as that is what Homebridge gets its data from, so sh*t in, sh*t out I guess. Also the fact that before you took over homebridge-gsh it already had this issue.

Thanks for now.

**Comment by vespino** [comment]
I sorta found what’s causing my issue: https://github.com/PatchworkBoy/homebridge-edomoticz/issues/286

**Comment by NorthernMan54** [comment]
Good to hear you found your issue

**Comment by vespino** [comment]
But not the solution. Not sure it’s eDomoticz or Google.

**Comment by PatchworkBoy** [comment]
EDomoticz exposes Domoticz devices with TV icon set as the _full-blown_ Apple SmartTV device type as per HomeKit spec, with input switching, now playing integration, vol up/down & channel up/down support.

It doesn't expose it as a plain light/switch/outlet (if you set icon in Domoticz to something other than TV, then it does, depending what type/icon you choose).

Alexa plugin treats this perfectly (I'm a paying subscriber 👍🏼), and Apple obvs handles perfectly. I don't use Google Home, so no idea how it ends up presenting once passing thru _this_ plugin.

**Comment by vespino** [comment]
Also: https://github.com/PatchworkBoy/homebridge-edomoticz/issues/286#issuecomment-2540752912

**Comment by NorthernMan54** [comment]
This is my Apple TV - From the homebridge-appletv-enhanced plugin

![IMG_7282](https://github.com/user-attachments/assets/cc2156b2-11d4-477c-9b35-a3554e400109)

Which shows up in Google as a `TV`

I think your issue is the incorrect Type here

![image](https://github.com/user-attachments/assets/9dcfd9c1-0ed2-4520-af2b-c48db6907bf3)

Take a look at what @PatchworkBoy has his set as

**Comment by vespino** [comment]
Nope, it’s on/off or dimmer.
![IMG_2029](https://github.com/user-attachments/assets/2c68273e-93d3-443b-a623-6ff31deaa4a9)

![IMG_2030](https://github.com/user-attachments/assets/190ed2d5-b4e6-48b2-89cf-2054fe0d0f61)

**Comment by NorthernMan54** [comment]
Looks like it needs to be Media Player - https://github.com/PatchworkBoy/homebridge-edomoticz/issues/286#issuecomment-2541729070

**Comment by vespino** [comment]
Although not exactly how I’d invisioned it, I changed all devices concerning my issue to “media player” and selected the icon I associate with its action. The devices are shown in Homebridge as TV and have an extra icon added to them, fine, the idea is not to use the Homebridge interface. I did hide the extra icons to please my ocd. In Google Home the devices are also shown as a TV, but since I mainly use Google Assistant to control the devices by speaking, this is also something I can deal with. When now asking Google to turn on/off the lights in my living room, only the lights are controlled and not the TV. Cheers.
